#ifndef __SCT_FSM_H__
#define __SCT_FSM_H__

/* Generated by fzmparser version 1.14 --- DO NOT EDIT! */

#include "sct_user.h"

extern void sct_fsm_init(void);

/* macros for defining the mapping between IRQ and events */
#define SCT_IRQ_EVENT_samplingComplete (11)

/* Input assignments */
#define SCT_INPUT_IN (3)

/* Output assignments (and their defaults if specified) */
#define SCT_OUTPUT_DONE (7)
#define SCT_OUTPUTPRELOAD_DONE (0)

/* Capture registers */
#define SCT_CAPTURE_sample2 LPC_SCT->CAP[0].U
#define SCT_CAPTURE_sample5 LPC_SCT->CAP[1].U
#define SCT_CAPTURE_sample7 LPC_SCT->CAP[2].U
#define SCT_CAPTURE_sample11 LPC_SCT->CAP[3].U
#define SCT_CAPTURE_sample4 LPC_SCT->CAP[4].U
#define SCT_CAPTURE_sample14 LPC_SCT->CAP[5].U
#define SCT_CAPTURE_sample3 LPC_SCT->CAP[6].U
#define SCT_CAPTURE_sample1 LPC_SCT->CAP[7].U
#define SCT_CAPTURE_sample6 LPC_SCT->CAP[8].U
#define SCT_CAPTURE_sample13 LPC_SCT->CAP[9].U
#define SCT_CAPTURE_sample12 LPC_SCT->CAP[10].U
#define SCT_CAPTURE_sample8 LPC_SCT->CAP[11].U
#define SCT_CAPTURE_sample15 LPC_SCT->CAP[12].U
#define SCT_CAPTURE_sample10 LPC_SCT->CAP[13].U
#define SCT_CAPTURE_sample9 LPC_SCT->CAP[14].U
#define SCT_CAPTURE_sample16 LPC_SCT->CAP[15].U


#endif
