
/* Generated by fzmparser version 2.2 --- DO NOT EDIT! */

/* Uses following resources: */
/* [6 events, 0+0 states, 1 inputs, 4 outputs, 5 match regs, 0 capture regs] */

#include "sct_fsm.h"


void sct_fsm_init (void)
{
LPC_SCT->CONFIG = (LPC_SCT->CONFIG & ~0x00060001) | 0x00000001; /* UNIFIED */

/* MATCH/CAPTURE registers */

/* Unified counter - register side L is used and accessed as 32 bit value, reg H is not used */
LPC_SCT->REGMODE_L = 0x00000000;         /* U: 5x MATCH, 0x CAPTURE, 0 unused */

LPC_SCT->MATCH[0].U = C_pwm_cycle;             /* pwm_cycle */
LPC_SCT->MATCHREL[0].U = C_pwm_cycle;
LPC_SCT->MATCH[1].U = C_pwm_val1;             /* pwm_val1 */
LPC_SCT->MATCHREL[1].U = C_pwm_val1;
LPC_SCT->MATCH[2].U = C_pwm_val2;             /* pwm_val2 */
LPC_SCT->MATCHREL[2].U = C_pwm_val2;
LPC_SCT->MATCH[3].U = C_pwm_val3;             /* pwm_val3 */
LPC_SCT->MATCHREL[3].U = C_pwm_val3;
LPC_SCT->MATCH[4].U = C_pwm_val4;             /* pwm_val4 */
LPC_SCT->MATCHREL[4].U = C_pwm_val4;

/* OUTPUT registers */
LPC_SCT->OUT[0].SET = 0x00000001;        /* PWM1 */
LPC_SCT->OUT[0].CLR = 0x00000022;
LPC_SCT->OUT[1].SET = 0x00000001;        /* PWM2 */
LPC_SCT->OUT[1].CLR = 0x00000006;
LPC_SCT->OUT[2].SET = 0x00000001;        /* PWM3 */
LPC_SCT->OUT[2].CLR = 0x0000000A;
LPC_SCT->OUT[3].SET = 0x00000001;        /* PWM4 */
LPC_SCT->OUT[3].CLR = 0x00000012;
LPC_SCT->OUTPUT = (LPC_SCT->OUTPUT & ~0x0000000F) | 0x00000000;

/* Conflict resolution register */

/* EVENT registers */
LPC_SCT->EVENT[0].CTRL = 0x00001000;     /* U: */
LPC_SCT->EVENT[0].STATE = 0xFFFFFFFF;
LPC_SCT->EVENT[1].CTRL = 0x00002000;     /* U: */
LPC_SCT->EVENT[1].STATE = 0xFFFFFFFF;
LPC_SCT->EVENT[2].CTRL = 0x00001002;     /* U: */
LPC_SCT->EVENT[2].STATE = 0xFFFFFFFF;
LPC_SCT->EVENT[3].CTRL = 0x00001003;     /* U: */
LPC_SCT->EVENT[3].STATE = 0xFFFFFFFF;
LPC_SCT->EVENT[4].CTRL = 0x00001004;     /* U: */
LPC_SCT->EVENT[4].STATE = 0xFFFFFFFF;
LPC_SCT->EVENT[5].CTRL = 0x00001001;     /* U: */
LPC_SCT->EVENT[5].STATE = 0xFFFFFFFF;

/* STATE registers */
LPC_SCT->STATE_L = 0; /* implicit value */

/* state names assignment: */

/* CORE registers */
LPC_SCT->START_L = 0x00000000;
LPC_SCT->STOP_L =  0x00000000;
LPC_SCT->HALT_L =  0x00000002;
LPC_SCT->LIMIT_L = 0x00000003;
LPC_SCT->EVEN =    0x00000003;

}
